spring:
  profiles:
    active: dev
camel.springboot.shutdownTimeout: 2
---

spring:
  profiles: dev

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: DEV profile

---
spring:
  profiles: stage

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: STAGE profile

---
spring:
  profiles: prod

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: PROD profile